import type { CardLayoutSchema } from 'km-card-schema';

export const blackGoldSchema: CardLayoutSchema = {
  id: 'kuanmai-black-gold',
  container: {
    mode: 'absolute',
  },
  width: 343,
  height: 210,
  fontColor: '#ffffff',
  padding: 20,
  children: [
    {
      id: 'company',
      type: 'text',
      binding: 'user.company',
      layout: {
        mode: 'absolute',
        x: 18,
        y: 16,
        width: 180,
        height: 20.8,
      },
      style: {
        fontSize: 16,
        color: '#ffffff',
        letterSpacing: 0.5,
        fontWeight: 400,
      },
    },
    {
      id: 'name',
      type: 'text',
      binding: 'user.name',
      layout: {
        mode: 'absolute',
        x: 18,
        y: 45,
        width: 140,
        height: 26,
      },
      style: {
        fontSize: 20,
        color: '#ffffff',
        fontWeight: 350,
      },
    },
    {
      id: 'duty',
      type: 'text',
      binding: 'user.duty',
      layout: {
        mode: 'absolute',
        x: 18,
        y: 81,
        width: 110,
        height: 20,
      },
      style: {
        fontSize: 13,
        color: '#ffffff',
        fontWeight: 200,
      },
    },
    {
      id: 'phone-dot',
      type: 'icon',
      name: 'company',
      layout: {
        mode: 'absolute',
        x: 18,
        y: 130,
        width: 20,
        height: 20,
      },
      style: {
        backgroundColor: '#ffffff',
        borderRadius: '50%',
        color: '#ffffff',
      },
      fontSize: 12,
    },
    {
      id: 'phone',
      type: 'text',
      binding: 'user.phone',
      layout: {
        mode: 'absolute',
        x: 40,
        y: 131,
        width: 150,
        height: 20,
      },
      style: {
        fontSize: 13,
        color: '#ffffff',
        fontWeight: 400,
      },
    },
    {
      id: 'email-dot',
      type: 'icon',
      name: 'company',
      layout: {
        mode: 'absolute',
        x: 18,
        y: 151,
        width: 20,
        height: 20,
      },
      style: {
        backgroundColor: '#ffffff',
        borderRadius: '50%',
        color: '#ffffff',
      },
      fontSize: 12,
    },
    {
      id: 'email',
      type: 'text',
      binding: 'user.email',
      layout: {
        mode: 'absolute',
        x: 40,
        y: 152,
        width: 160,
        height: 20,
      },
      style: {
        fontSize: 13,
        color: '#ffffff',
        fontWeight: 400,
      },
    },
    {
      id: 'address-dot',
      type: 'icon',
      name: 'company',
      layout: {
        mode: 'absolute',
        x: 18,
        y: 173,
        width: 20,
        height: 20,
      },
      style: {
        backgroundColor: '#ffffff',
        borderRadius: '50%',
        color: '#ffffff',
      },
      fontSize: 12,
    },
    {
      id: 'address',
      type: 'text',
      binding: 'user.address',
      layout: {
        mode: 'absolute',
        x: 40,
        y: 175,
        width: 271,
        height: 20,
      },
      style: {
        fontSize: 13,
        color: '#ffffff',
        lineHeight: 14,
        fontWeight: 400,
      },
    },
    {
      id: 'avatar',
      type: 'image',
      binding: 'user.avatar',
      layout: {
        mode: 'absolute',
        x: 246,
        y: 16,
        width: 80,
        height: 80,
      },
      style: {
        borderRadius: '50%',
        color: '#ffffff',
      },
    },
  ],
  backgroundImage:
    'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=900&q=60',
};
