import type { CardLayoutSchema } from 'km-card-schema';

export const crimsonWaveSchema: CardLayoutSchema = {
  id: 'kuanmai-crimson-wave',
  container: {
    mode: 'absolute',
  },
  width: 343,
  height: 210,
  padding: 20,
  fontColor: '#2b2b2b',
  backgroundImage:
    'https://km-1257079185.cos.ap-chengdu.myqcloud.com/static/cardstyleV3/bg_big_15.png',
  children: [
    {
      id: 'name',
      type: 'text',
      binding: 'user.name',
      style: {
        fontSize: 16,
        color: '#A67D27',
        fontWeight: 350,
        textAlign: 'right',
      },
      layout: {
        mode: 'absolute',
        x: 10,
        y: 64.5,
        width: 83.5,
        height: 20.8,
      },
    },
    {
      id: 'mobile-dot',
      type: 'icon',
      name: 'mobile ',
      fontSize: 10,
      color: '#A67D27',
      style: {
        color: '#A67D27',
      },
      layout: {
        mode: 'absolute',
        x: 145,
        y: 50,
        width: 8,
        height: 8,
      },
    },
    {
      id: 'email-dot',
      type: 'icon',
      name: 'email',
      style: {
        backgroundColor: '#fff',
        borderRadius: '50%',
        color: '#A67D27',
      },
      color: '#A67D27',
      layout: {
        mode: 'absolute',
        x: 145,
        y: 71,
        width: 8,
        height: 8,
      },
    },
    {
      id: 'address-dot',
      type: 'icon',
      name: 'address',
      fontSize: 10,
      style: {
        color: '#A67D27',
      },
      color: '#A67D27',
      layout: {
        mode: 'absolute',
        x: 145,
        y: 116.5,
        width: 8,
        height: 8,
      },
    },
    {
      id: 'company-dot',
      type: 'icon',
      name: 'company',
      fontSize: 10,
      color: '#A67D27',
      style: {
        color: '#A67D27',
      },
      layout: {
        mode: 'absolute',
        x: 145,
        y: 95,
        width: 8,
        height: 8,
      },
    },
    {
      id: 'duty',
      type: 'text',
      binding: 'user.duty',
      style: {
        fontSize: 11,
        color: '#858585',
        textAlign: 'right',
        fontWeight: 'normal',
      },
      layout: {
        mode: 'absolute',
        x: 8.5,
        y: 91,
        width: 85,
        height: 32.5,
      },
    },
    {
      id: 'mobile',
      type: 'text',
      binding: 'user.mobile',
      style: {
        fontSize: 11,
        color: '#858585',
        fontWeight: 'normal',
      },
      layout: {
        mode: 'absolute',
        x: 161.5,
        y: 46,
        width: 163,
        height: 16,
      },
    },
    {
      id: 'email',
      type: 'text',
      binding: 'user.email',
      style: {
        fontSize: 11,
        color: '#858585',
        fontWeight: 'normal',
      },
      layout: {
        mode: 'absolute',
        x: 162.5,
        y: 67,
        width: 154,
        height: 16,
      },
    },
    {
      id: 'company',
      type: 'text',
      binding: 'user.company',
      style: {
        fontSize: 11,
        color: '#858585',
        fontWeight: 'normal',
      },
      layout: {
        mode: 'absolute',
        x: 161.5,
        y: 91,
        width: 164,
        height: 16,
      },
    },
    {
      id: 'address',
      type: 'text',
      binding: 'user.address',
      style: {
        fontSize: 11,
        color: '#858585',
        lineHeight: 13,
        fontWeight: 'normal',
      },
      layout: {
        mode: 'absolute',
        x: 161,
        y: 113,
        width: 170,
        height: 30.5,
      },
    },
  ],
};
