export const version = '0.1.0';

/**
 * Quick helper that lets you confirm the runtime bundle that was generated by the build step.
 * You can remove it once your own exports are in place.
 */
export function describe() {
  return `TDesign Miniprogram starter v${version}`;
}
